# Generated by Django 6.1.1 on 2026-09-06 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('done_by', models.CharField(max_length=200)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['chore_name', 'period_start'], name='chores_comp_chore_n_37531c_idx')],
            },
        ),
    ]
