# Generated by Django 6.1.1 on 2026-09-06 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore_name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('covered_by', models.CharField(max_length=200)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['period_start', 'chore_name'],
                'constraints': [models.UniqueConstraint(fields=('chore_name', 'period_start'), name='unique_swap_per_chore_period')],
            },
        ),
    ]
