"""create parties table

Revision ID: 11389b27b399
Revises: 
Create Date: 2026-09-13 15:28:11.519830

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11389b27b399'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'parties',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('party_size', sa.Integer(), nullable=False),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('quoted_minutes', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'waiting' AND ended_at IS NULL) OR "
            "(status != 'waiting' AND ended_at IS NOT NULL)",
            name='ck_parties_waiting_iff_ended_at_null',
        ),
        sa.CheckConstraint('party_size >= 1', name='ck_parties_party_size_positive'),
        sa.CheckConstraint(
            'quoted_minutes IS NULL OR quoted_minutes >= 0',
            name='ck_parties_quoted_minutes_non_negative',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_parties_status_created_at', 'parties', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parties_status_created_at', table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
